// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQjo5H8RWQSxhB5Byn2ZZCaBaNpMQsfWM',
    appId: '1:581025774991:web:66a2fc71ce3bf175ba9ffa',
    messagingSenderId: '581025774991',
    projectId: 'waste-a2ae0',
    authDomain: 'waste-a2ae0.firebaseapp.com',
    storageBucket: 'waste-a2ae0.firebasestorage.app',
    measurementId: 'G-FBYG369DSP',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdIvIxxcIT-zZXDvKOQexAqusf8nxVwcA',
    appId: '1:581025774991:ios:f2c256dae47f9abfba9ffa',
    messagingSenderId: '581025774991',
    projectId: 'waste-a2ae0',
    storageBucket: 'waste-a2ae0.firebasestorage.app',
    iosBundleId: 'com.example.tempProject',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoGG8zCH22xR2qVqOtpAPCY7bQxhac9TM',
    appId: '1:581025774991:android:043cfea79ac81562ba9ffa',
    messagingSenderId: '581025774991',
    projectId: 'waste-a2ae0',
    storageBucket: 'waste-a2ae0.firebasestorage.app',
  );

}